server:
  port: ${APP_PORT:8089}

spring:
  application:
    name: RhythmApi
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  security:
    enabled: false
  data:
    mongodb:
      uri : mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.4
      database : rhythm_db
      # ssl :
      #   enabled: true
Rhythm:
  app:
    jwtSecret: your-secret-key
    jwtExpirationMs: 3600000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    name: logs/rhythm-api.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
