server:
  port: ${APP_PORT:8089}
  tomcat:
    max-swallow-size: 1000MB
    max-http-form-post-size: 1000MB

spring:
  application:
    name: RhythmApi
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  security:
    filter:
      order: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
      resolve-lazily: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27018/rhythmdb}
  mvc:
    log-request-details: true

rhythm:
  app:
    jwtSecret: ${JWT_SECRET:defaultSecretKeyWhichShouldBeChangedInProduction}
    jwtExpirationMs: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    com.yc.Rhythm: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# ... (rest of the configuration remains the same)

