server:
  port: ${APP_PORT:8089}

spring:
  application:
    name: RhythmApi
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  # security:
  #   enabled: false

Rhythm:
  app:
    jwtSecret: your-secret-key
    jwtExpirationMs: 10600000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    name: logs/rhythm-api.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

 # Swagger Configuration
springfox:
  documentation:
    swagger-ui:
      path: /swagger-ui.html
